// Generated by gencpp from file ros_plane/Controller_Internals.msg
// DO NOT EDIT!


#ifndef ROS_PLANE_MESSAGE_CONTROLLER_INTERNALS_H
#define ROS_PLANE_MESSAGE_CONTROLLER_INTERNALS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_plane
{
template <class ContainerAllocator>
struct Controller_Internals_
{
  typedef Controller_Internals_<ContainerAllocator> Type;

  Controller_Internals_()
    : theta_c(0.0)
    , phi_c(0.0)
    , alt_zone(0)
    , aux()
    , aux_valid(false)  {
      aux.assign(0.0);
  }
  Controller_Internals_(const ContainerAllocator& _alloc)
    : theta_c(0.0)
    , phi_c(0.0)
    , alt_zone(0)
    , aux()
    , aux_valid(false)  {
  (void)_alloc;
      aux.assign(0.0);
  }



   typedef float _theta_c_type;
  _theta_c_type theta_c;

   typedef float _phi_c_type;
  _phi_c_type phi_c;

   typedef uint8_t _alt_zone_type;
  _alt_zone_type alt_zone;

   typedef boost::array<float, 4>  _aux_type;
  _aux_type aux;

   typedef uint8_t _aux_valid_type;
  _aux_valid_type aux_valid;


    enum { ZONE_TAKE_OFF = 0u };
     enum { ZONE_CLIMB = 1u };
     enum { ZONE_DESEND = 2u };
     enum { ZONE_ALTITUDE_HOLD = 3u };
 

  typedef boost::shared_ptr< ::ros_plane::Controller_Internals_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_plane::Controller_Internals_<ContainerAllocator> const> ConstPtr;

}; // struct Controller_Internals_

typedef ::ros_plane::Controller_Internals_<std::allocator<void> > Controller_Internals;

typedef boost::shared_ptr< ::ros_plane::Controller_Internals > Controller_InternalsPtr;
typedef boost::shared_ptr< ::ros_plane::Controller_Internals const> Controller_InternalsConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_plane::Controller_Internals_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_plane::Controller_Internals_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_plane

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ros_plane': ['/home/magiccjae/jae_stuff/classes/ee773/project/catkin_ws/src/ros_plane/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_plane::Controller_Internals_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_plane::Controller_Internals_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_plane::Controller_Internals_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_plane::Controller_Internals_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_plane::Controller_Internals_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_plane::Controller_Internals_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_plane::Controller_Internals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d7fa61846cd31497d4b102451fa214b";
  }

  static const char* value(const ::ros_plane::Controller_Internals_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d7fa61846cd3149ULL;
  static const uint64_t static_value2 = 0x7d4b102451fa214bULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_plane::Controller_Internals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_plane/Controller_Internals";
  }

  static const char* value(const ::ros_plane::Controller_Internals_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_plane::Controller_Internals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Controller internals (inner loops, states) output from the autopilot controller, for now just for debuging and ploting\n\
\n\
# @warning theta_c, phi_c and alt_zone have always to be valid, the aux array is optional\n\
float32 theta_c		# Commanded pitch (rad)\n\
float32 phi_c		# Commanded roll (rad)\n\
uint8 alt_zone		# Zone in the altitude state machine\n\
float32[4] aux		# Optional auxiliary commands\n\
bool aux_valid		# Auxiliary commands valid\n\
\n\
uint8 ZONE_TAKE_OFF = 0\n\
uint8 ZONE_CLIMB = 1\n\
uint8 ZONE_DESEND = 2\n\
uint8 ZONE_ALTITUDE_HOLD = 3\n\
";
  }

  static const char* value(const ::ros_plane::Controller_Internals_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_plane::Controller_Internals_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta_c);
      stream.next(m.phi_c);
      stream.next(m.alt_zone);
      stream.next(m.aux);
      stream.next(m.aux_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Controller_Internals_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_plane::Controller_Internals_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_plane::Controller_Internals_<ContainerAllocator>& v)
  {
    s << indent << "theta_c: ";
    Printer<float>::stream(s, indent + "  ", v.theta_c);
    s << indent << "phi_c: ";
    Printer<float>::stream(s, indent + "  ", v.phi_c);
    s << indent << "alt_zone: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.alt_zone);
    s << indent << "aux[]" << std::endl;
    for (size_t i = 0; i < v.aux.size(); ++i)
    {
      s << indent << "  aux[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.aux[i]);
    }
    s << indent << "aux_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.aux_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_PLANE_MESSAGE_CONTROLLER_INTERNALS_H
