// Generated by gencpp from file ros_copter/AddWaypoint.msg
// DO NOT EDIT!


#ifndef ROS_COPTER_MESSAGE_ADDWAYPOINT_H
#define ROS_COPTER_MESSAGE_ADDWAYPOINT_H

#include <ros/service_traits.h>


#include <ros_copter/AddWaypointRequest.h>
#include <ros_copter/AddWaypointResponse.h>


namespace ros_copter
{

struct AddWaypoint
{

typedef AddWaypointRequest Request;
typedef AddWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddWaypoint
} // namespace ros_copter


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_copter::AddWaypoint > {
  static const char* value()
  {
    return "7cfdc1b052a1b4a9bf3df9443ff04be6";
  }

  static const char* value(const ::ros_copter::AddWaypoint&) { return value(); }
};

template<>
struct DataType< ::ros_copter::AddWaypoint > {
  static const char* value()
  {
    return "ros_copter/AddWaypoint";
  }

  static const char* value(const ::ros_copter::AddWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::ros_copter::AddWaypointRequest> should match 
// service_traits::MD5Sum< ::ros_copter::AddWaypoint > 
template<>
struct MD5Sum< ::ros_copter::AddWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_copter::AddWaypoint >::value();
  }
  static const char* value(const ::ros_copter::AddWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_copter::AddWaypointRequest> should match 
// service_traits::DataType< ::ros_copter::AddWaypoint > 
template<>
struct DataType< ::ros_copter::AddWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::ros_copter::AddWaypoint >::value();
  }
  static const char* value(const ::ros_copter::AddWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_copter::AddWaypointResponse> should match 
// service_traits::MD5Sum< ::ros_copter::AddWaypoint > 
template<>
struct MD5Sum< ::ros_copter::AddWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_copter::AddWaypoint >::value();
  }
  static const char* value(const ::ros_copter::AddWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_copter::AddWaypointResponse> should match 
// service_traits::DataType< ::ros_copter::AddWaypoint > 
template<>
struct DataType< ::ros_copter::AddWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::ros_copter::AddWaypoint >::value();
  }
  static const char* value(const ::ros_copter::AddWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_COPTER_MESSAGE_ADDWAYPOINT_H
