// Generated by gencpp from file ros_copter/RemoveWaypoint.msg
// DO NOT EDIT!


#ifndef ROS_COPTER_MESSAGE_REMOVEWAYPOINT_H
#define ROS_COPTER_MESSAGE_REMOVEWAYPOINT_H

#include <ros/service_traits.h>


#include <ros_copter/RemoveWaypointRequest.h>
#include <ros_copter/RemoveWaypointResponse.h>


namespace ros_copter
{

struct RemoveWaypoint
{

typedef RemoveWaypointRequest Request;
typedef RemoveWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveWaypoint
} // namespace ros_copter


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_copter::RemoveWaypoint > {
  static const char* value()
  {
    return "8e64718d0fc1826ffd884d37ef95c787";
  }

  static const char* value(const ::ros_copter::RemoveWaypoint&) { return value(); }
};

template<>
struct DataType< ::ros_copter::RemoveWaypoint > {
  static const char* value()
  {
    return "ros_copter/RemoveWaypoint";
  }

  static const char* value(const ::ros_copter::RemoveWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::ros_copter::RemoveWaypointRequest> should match 
// service_traits::MD5Sum< ::ros_copter::RemoveWaypoint > 
template<>
struct MD5Sum< ::ros_copter::RemoveWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_copter::RemoveWaypoint >::value();
  }
  static const char* value(const ::ros_copter::RemoveWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_copter::RemoveWaypointRequest> should match 
// service_traits::DataType< ::ros_copter::RemoveWaypoint > 
template<>
struct DataType< ::ros_copter::RemoveWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::ros_copter::RemoveWaypoint >::value();
  }
  static const char* value(const ::ros_copter::RemoveWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_copter::RemoveWaypointResponse> should match 
// service_traits::MD5Sum< ::ros_copter::RemoveWaypoint > 
template<>
struct MD5Sum< ::ros_copter::RemoveWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_copter::RemoveWaypoint >::value();
  }
  static const char* value(const ::ros_copter::RemoveWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_copter::RemoveWaypointResponse> should match 
// service_traits::DataType< ::ros_copter::RemoveWaypoint > 
template<>
struct DataType< ::ros_copter::RemoveWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::ros_copter::RemoveWaypoint >::value();
  }
  static const char* value(const ::ros_copter::RemoveWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_COPTER_MESSAGE_REMOVEWAYPOINT_H
