// Generated by gencpp from file ros_copter/RemoveWaypointRequest.msg
// DO NOT EDIT!


#ifndef ROS_COPTER_MESSAGE_REMOVEWAYPOINTREQUEST_H
#define ROS_COPTER_MESSAGE_REMOVEWAYPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_copter
{
template <class ContainerAllocator>
struct RemoveWaypointRequest_
{
  typedef RemoveWaypointRequest_<ContainerAllocator> Type;

  RemoveWaypointRequest_()
    : front(false)  {
    }
  RemoveWaypointRequest_(const ContainerAllocator& _alloc)
    : front(false)  {
  (void)_alloc;
    }



   typedef uint8_t _front_type;
  _front_type front;




  typedef boost::shared_ptr< ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RemoveWaypointRequest_

typedef ::ros_copter::RemoveWaypointRequest_<std::allocator<void> > RemoveWaypointRequest;

typedef boost::shared_ptr< ::ros_copter::RemoveWaypointRequest > RemoveWaypointRequestPtr;
typedef boost::shared_ptr< ::ros_copter::RemoveWaypointRequest const> RemoveWaypointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_copter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "676ebc8a66a9b28b5a67383251f04ff0";
  }

  static const char* value(const ::ros_copter::RemoveWaypointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x676ebc8a66a9b28bULL;
  static const uint64_t static_value2 = 0x5a67383251f04ff0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_copter/RemoveWaypointRequest";
  }

  static const char* value(const ::ros_copter::RemoveWaypointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
bool front\n\
";
  }

  static const char* value(const ::ros_copter::RemoveWaypointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.front);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoveWaypointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_copter::RemoveWaypointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_copter::RemoveWaypointRequest_<ContainerAllocator>& v)
  {
    s << indent << "front: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.front);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_COPTER_MESSAGE_REMOVEWAYPOINTREQUEST_H
