// Generated by gencpp from file ros_copter/SetWaypointsFromFile.msg
// DO NOT EDIT!


#ifndef ROS_COPTER_MESSAGE_SETWAYPOINTSFROMFILE_H
#define ROS_COPTER_MESSAGE_SETWAYPOINTSFROMFILE_H

#include <ros/service_traits.h>


#include <ros_copter/SetWaypointsFromFileRequest.h>
#include <ros_copter/SetWaypointsFromFileResponse.h>


namespace ros_copter
{

struct SetWaypointsFromFile
{

typedef SetWaypointsFromFileRequest Request;
typedef SetWaypointsFromFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetWaypointsFromFile
} // namespace ros_copter


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_copter::SetWaypointsFromFile > {
  static const char* value()
  {
    return "93a4bc4c60dc17e2a69e3fcaaa25d69d";
  }

  static const char* value(const ::ros_copter::SetWaypointsFromFile&) { return value(); }
};

template<>
struct DataType< ::ros_copter::SetWaypointsFromFile > {
  static const char* value()
  {
    return "ros_copter/SetWaypointsFromFile";
  }

  static const char* value(const ::ros_copter::SetWaypointsFromFile&) { return value(); }
};


// service_traits::MD5Sum< ::ros_copter::SetWaypointsFromFileRequest> should match 
// service_traits::MD5Sum< ::ros_copter::SetWaypointsFromFile > 
template<>
struct MD5Sum< ::ros_copter::SetWaypointsFromFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_copter::SetWaypointsFromFile >::value();
  }
  static const char* value(const ::ros_copter::SetWaypointsFromFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_copter::SetWaypointsFromFileRequest> should match 
// service_traits::DataType< ::ros_copter::SetWaypointsFromFile > 
template<>
struct DataType< ::ros_copter::SetWaypointsFromFileRequest>
{
  static const char* value()
  {
    return DataType< ::ros_copter::SetWaypointsFromFile >::value();
  }
  static const char* value(const ::ros_copter::SetWaypointsFromFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_copter::SetWaypointsFromFileResponse> should match 
// service_traits::MD5Sum< ::ros_copter::SetWaypointsFromFile > 
template<>
struct MD5Sum< ::ros_copter::SetWaypointsFromFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_copter::SetWaypointsFromFile >::value();
  }
  static const char* value(const ::ros_copter::SetWaypointsFromFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_copter::SetWaypointsFromFileResponse> should match 
// service_traits::DataType< ::ros_copter::SetWaypointsFromFile > 
template<>
struct DataType< ::ros_copter::SetWaypointsFromFileResponse>
{
  static const char* value()
  {
    return DataType< ::ros_copter::SetWaypointsFromFile >::value();
  }
  static const char* value(const ::ros_copter::SetWaypointsFromFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_COPTER_MESSAGE_SETWAYPOINTSFROMFILE_H
